# Generated by Django 4.2.6 on 2023-10-24 22:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pokemon", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pokemon",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("norm", "normal"),
                    ("agua", "água"),
                    ("fogo", "fogo"),
                    ("gram", "grama"),
                ],
                default="norm",
                max_length=4,
            ),
        ),
    ]
