# Generated by Django 4.2.6 on 2023-10-31 22:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pokemon", "0005_pokeamb_alter_pokemon_ambientes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pokemon",
            name="habitat",
        ),
        migrations.AddField(
            model_name="pokemon",
            name="capturado",
            field=models.BooleanField(default=False),
        ),
    ]
